In [224]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b> While Loops </b>

In [3]:
x=True
while x:
    print('x is True')
    x=False
else:
    print('x is False')

x is True
x is False


In [7]:
decision=input('Are you well? (y/n)')
while decision !='y' and decision!='n':
    decision=input('What? Please enter whether you are well:')

Are you well? (y/n)nnn
What? Please enter whether you are well:y


In [8]:
count = 0
while True:
    print(count)
    count+=1
    if count>=10:
        break

0
1
2
3
4
5
6
7
8
9


<b> Tuples </b>

In [10]:
x='a',

In [11]:
type(x)

tuple

<b> Enumerate </b>

In [16]:
for j, x in enumerate(('d','b','f')):
    print('{},{}'.format(j,x))#print("{}".format(x)

0,d
1,b
2,f


In [7]:
for index, x in enumerate(('a1','b1','c1','d1','e1')):
    print('{1} is the value \n\
{0}  is the index'.format(index,x))

a1 is the value 
0  is the index
b1 is the value 
1  is the index
c1 is the value 
2  is the index
d1 is the value 
3  is the index
e1 is the value 
4  is the index


#### For loops

In [20]:
for j in 'Coming over the bridge, we saw the sun rise':
    print(j), #use a comma to have text stay on same line

C o m i n g   o v e r   t h e   b r i d g e ,   w e   s a w   t h e   s u n   r i s e


In [51]:
d={'a': 'apple', 'b': 'berry', 'c': 'cherry'}
for key in d:
    print('Key: {1} \
Value: {0}'.format(d[key],key)) 

Key: a Value: apple
Key: c Value: cherry
Key: b Value: berry


In [ ]:
pd.DataFrame({'name':[11,,11]})

In [172]:
import pandas as pd
df=pd.DataFrame({'Cost':[1,2,3,4],
              'Item':['Jacket','Jeans',
                     'Tee-Shirt','Pea Coat']})

for price, product in zip(df['Cost'],df['Item']):
    if product == 'Pea Coat':
        continue
    if (price > 2) | (product == 'Jacket'):
        print("Price:   {1} \
               Product: {0}".format(product, price))
    elif product == 'Jeans':
        print('It\'s {}!'.format(product))
    else:
        print(False)
#| requires   (v) | (v)
#or only requires   v | v

Price:   1                Product: Jacket
It's Jeans!
Price:   3                Product: Tee-Shirt


#### list comprehensions

In [412]:
[x for x in range(1,6)]
[x^2 for x in range(1,5)]
[x^2 for x in range(1,5) if x>3]
[x^2+y^2 for x in range(1,5) if x>3
         for y in range(1,5) if y>2]
#12345
#12345

[1, 2, 3, 4, 5]

[3, 0, 1, 6]

[6]

[3, 0]

#### pandas

In [65]:
import pandas as pd
pd.DataFrame({'Cost':[1,2,3,4]})
pd.DataFrame([1,2,3,4],columns=['Cost2'])

df=pd.DataFrame({'Cost':[1,2,3,4],
              'Item':['Jacket','Jeans',
                     'Tee-Shirt','Pea Coat']})

Cost2
0      1
1      2
2      3
3      4

In [145]:
df[:] #all
df[1:] #row 1 +
df[:2] #row 0 and 1
df[0:1] #row 0
df['Item'] #column item
df.values #produce each row as an array in a np array
df.ix[0:'Item'] #DEPRECATED
df.loc[2,'Item'] #select by row name and column name
df.iloc[0,1] #select by row position and column position
df.rename(columns={'Item':'Product'},inplace=True) 
#inplace = True replaces the original dataframe

KeyError: 'Item'

In [154]:
df.index=range(1,5) #change row index to 1:4
df.index=range(0,4) #change row index to 0:3
df['Price'][[1]] #keeps output as a series (shows index)
df['Price'][1] #outputs value at index 1

1    2
Name: Price, dtype: int64

In [199]:
df=pd.DataFrame({'Cost':[1,2,3,4],
              'Item':['Jacket','Jeans',
                     'Tee-Shirt','Pea Coat']})
df2=pd.get_dummies(df) # create binary vars for nominals
df3=df
df3['Expense']=[3,2,1,4]
df # doing df3=df means any changes to df3 affects df
import copy
del(df['Expense']) #delete column
df3=copy.deepcopy(df) #use this DF copy method
df3['Expense']=[3,2,1,4]
df3.rename(columns={'Cost':'Price'},inplace=True)

Cost       Item  Expense
0     1     Jacket        3
1     2      Jeans        2
2     3  Tee-Shirt        1
3     4   Pea Coat        4

In [259]:
profitable=[]
for price,expense in zip(df3['Price'],df3['Expense']):
    if price > expense:
        profitable.append(df3[df3['Price']==price].\
                          index.values)
profitable_items=df3.iloc[profitable[0],:]
profitable_items

Price       Item  Expense
2      3  Tee-Shirt        1

#### Using Numpy

In [9]:
import numpy as np
#https://realpython.com/numpy-array-programming/

In [263]:
np.matrix?

In [12]:
?np.array

In [271]:
#an array of shape (n1, n2, ...nj) has n dimensions (=length (shape))
#the # of dimensions is called its rank, and each dim has size nj 
np.arange(10).reshape(2,5) #2 arrays / dimensions of size 5
#5 arrays, each has 2 arrays, each has 2 arrays of size 2
array_object=np.arange(20).reshape(5,2,2) #(dim1 size, dim2 size, dim3 s)
array_object
array_object[0] #subset 1st of 5 arrays
array_object[0,1] #subset 1st array of 5, 2nd array of 2
array_object[0:2] #subset 1st two arrays of 5
array_object.shape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

array([[0, 1],
       [2, 3]])

array([2, 3])

In [353]:
#You can pass dfs or series to numpy methods
#You can convert dfs or series to numpy arrays (.values)
np.log10(df['Cost'].values)
np.log10(df['Cost'])

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999])

0    0.000000
1    0.301030
2    0.477121
3    0.602060
Name: Cost, dtype: float64

In [ ]:
np.zeros((3,2,4)) #dtype='int'
np.empty((3,2,4)) 
np.ones((3,2,4))
np.arange(0,20,2)
np.random.normal(0,1,(3,2,4))  #3D array
np.random.randint(20,size=(2,2))
np.random.seed(1) #stick first to make reproducible

### pandas vectorization methods

In [392]:
df_numerics=pd.DataFrame(df3[['Price','Expense']])

#df vectorization method
df_numerics.apply(np.mean,axis=0) 
df_numerics.apply(np.mean) #apply to each column
df_numerics.applymap(np.log10) #apply to each element

#series vectorization method
df_numerics['Price'].map(np.log10) #apply to each element
df_numerics['Price'].apply(np.log10) 
#you can do above but its less efficient
#it works on whole rows for dataframes (USE MAP!!!)

Price      2.5
Expense    2.5
dtype: float64

Price      2.5
Expense    2.5
dtype: float64

Price   Expense
0  0.000000  0.477121
1  0.301030  0.301030
2  0.477121  0.000000
3  0.602060  0.602060

0    0.000000
1    0.301030
2    0.477121
3    0.602060
Name: Price, dtype: float64